import Head from 'next/head'

// layout
import BaseLayout from '/layouts/Base'

export default function Home() {
  return (
    <>
      <Head>
        <title>DEMO</title>
        <meta name="description" content="Generated by DEMO" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <BaseLayout>
        <h1>Hello Next.js</h1>
      </BaseLayout>

    </>
  )
}
