import Head from 'next/head'
import { useContext } from 'react'

import { useMenu } from '../store/context/MenuContext'

// layout
import BaseLayout from '/layouts/Base'

export default function Home() {
  const [isMenuOpen, setIsMenuOpen] = useMenu();

  return (
    <>
      <Head>
        <title>DEMO</title>
        <meta name="description" content="Generated by DEMO" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <BaseLayout>
        <h1>Hello Next.js</h1>
        { isMenuOpen ? <p>Menu is open</p> : <p>Menu is closed</p> }
      </BaseLayout>

    </>
  )
}
